### ISSUE TITLE
Cant mine copper with water

### ISSUE THREAD

**Issue by Indzasa** [notnotmelon/pyhardmode#1]
![image](https://github.com/notnotmelon/pyhardmode/assets/6001996/1be29343-3d2f-4584-923f-ef0c94ec05e7)
On the screenshot it is shown that i cant get copper ore though i have lots of water.
Raw coal is inside mining drill, water is being pumped around unto it.

**Comment by notnotmelon** [comment]
Fixed! Thank you.
