### ISSUE TITLE
Factorio 2.0: Tailing dust separation recipe disabled

### ISSUE THREAD

**Issue by feschka97** [notnotmelon/pyhardmode#16]
There are no way to use tailing-dust until sci-pack 3. The native pyanodons pack has a way to void it, but pyhardmode seem to disable it in 2.0 (it was enabled before)

The separation technology with pyhardmode:
![image](https://github.com/user-attachments/assets/e2d3c833-3379-4abd-8dc3-04760923a179)

![image](https://github.com/user-attachments/assets/a0fd11db-4a33-463a-974c-2b7d062a499f)

The tech in the "original" py:
![image](https://github.com/user-attachments/assets/a4909b9e-691b-43fe-a3b9-fb7a753c4d41)

Let me know if this is intended!

**Comment by notnotmelon** [comment]
Thanks. This is actually a bug in alternative energy. It's been fixed and released to the mod portal.
