### ISSUE TITLE
Burner miner fluid connections suggestion

### ISSUE THREAD

**Issue by TheFirstPaige1** [notnotmelon/pyhardmode#28]
As Py Hard Mode causes copper and stone to require mining fluid to mine, and so the early game experience has one using burner miners with fluid inputs, I would suggest the fluid connections be changed to pass-through connections on either side, perpendicular to the output, similar to how the gas furnace is. The current fluid connection is really difficult to work with at scale or in patterns that tesselate well.

**Comment by notnotmelon** [comment]
This is part of the challenge. I have seen many cool setups to work around this limitation.
