### ISSUE TITLE
Stack Inserter Tech does not require Fast Inserters

### ISSUE THREAD

**Issue by Morokael** [notnotmelon/pyhardmode#31]
Transport Belt Capacity can be researched before Fast Inserter.

The Stack Inserter recipe given by TBC requires Fast Inserters in order to build

**Comment by notnotmelon** [comment]
Thanks for the report. The tech tree is generated automatically via py post processing. pyPP is not yet updated for 2.0 however once its updated this issue will automatically be resolved.
