### ISSUE TITLE
"dump" hotkey on pipes not disabled in a new game

### ISSUE THREAD

**Issue by nicolasechcat** [notnotmelon/pyhardmode#33]
I just started yesteday a new game and realized that I can click the "dump" button in pipes with thousands of fluid and it let's me void it instead of the prior message and inhability to void it. I have all the optional dependencies expcept pyblock and I don't see any mod that can be interfering (other than py mods I have things like bottleneck little that do not intervene in fuid system).

I add the map exchange string:

>>>eNp1VD1oFEEU3sl5Xi6XHBGCEggxRQoRViSKVbhdf0BtrO3C7N5cbsjuzDo7mz8Lr0glggiCmEbrKFoLgoKNggHBQuyiNoIWQcU2vtm9uczuxoGZvP2+N+97P3MZsizrGGxrromDJKSMJqEtuL/0ZGurZVk9B7Y7gpmkIVdcBrspPOpRmYSE2TEhkUE4VY8LvGq6jvldwcODYh/yOQ5M17oCyin4PIqIsLkgpnOjDxfd675I2sTmNBd6hDASrtkejknfMd3ji4TLLhEh6PoC5yMNU8FZUbaegiXRgOB2CW2GPFjz2oRB8YUwowwnyzRe8APa6ZgNbDDqL5FyF2qMcq8whWEo0o4xa+f6DUr2YKAm01SMR+GMiVjOp6MoPai8BBCquFzrFcjIKgmozDU5xdP8S/CNBAu5bsI1BUvKSnlIKjE7KI91yvxcQVGXx1EXS1Jq15E8ZZ+eM9lGlk35lsAgQ4Dr2h4PaJvk3oPAK3bxzVYEyb8PQRbhpiSxebWqlGJzzvUYB7KUwNFYgjhliwuQCF4IOY1lkns5TjWWnOWHFydBJxF2hKXfzSUMkUoSY7q9JaYqoZbY/Hk0EpG5Fl+vxkvBl3ngA+XbEY1yzauuwCxEFqDfATXOUgQL3Xu6Pd/bmLbU3rtlzeztqQ3WDvyvUttCPbgB3ghAvarpLwmMmfOwLwyqQAjdnHh2+cv6fQdlnqfcvrHbR157GrmqjWvuf6lZbZw14pxJ12/DyEQlSPS9ht19IyM3FInQlecvN3992moh++LUj6/nTjp95HYLyJoqd2hwbD5U64UuxdIxd5w+9dlB2+/V+umgqroxoQ53EpR6Dw5baLwJn4/vwDEzZenUWjrMhIs66fqrK/mmjY9OsQ5oxLwKPq2Ot+pIBQeZocx077rIPa7ZyX0XuD9nmTm09yt8p2XfGPqFRMqDMOsoILPuAWMYUYLtwfG9MsgG+vmhpr/cRy6qKEN5/QEs+1KMDpX9HXfTdlcGj3LXyb80Zaggr05cuv4PM2j37w==<<<

**Comment by notnotmelon** [comment]
Thanks for the report. No fluid voiding was previously handled by this mod https://mods.factorio.com/mod/undeletable-fluids
However it is not ported into 2.0
Once this mod is ported I will readd the dependency.
