### ISSUE TITLE
HM + Pyblock cache

### ISSUE THREAD

**Issue by Shinozoa** [notnotmelon/pyhardmode#4]
![image](https://github.com/notnotmelon/pyhardmode/assets/93893109/0938cba1-381d-4023-8b51-aaf7521e1c2f)

Quintuple [PyAE, close to py2] — 11/21/2023 10:41 PM
Erkigmo is right, notnotmelon made a cache file for HM but not one for HM+PyBlock, so the cache file system complains because it doesn’t know which one to apply (HM or PyBlock). If you want a workaround, you can remove the cache registration call for the HM cache in data-updates.lua in HM, and then you’ll use the PyBlock cache which should work until very late game

**Comment by notnotmelon** [comment]
Fixed
